# Generated by Django 4.0 on 2021-12-29 00:04

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=80)),
                ('yr', models.IntegerField(db_index=True, verbose_name=django.core.validators.RegexValidator('^[0-9]{4}$', 'Fomrat: XXXX'))),
                ('score', models.FloatField()),
                ('votes', models.IntegerField()),
                ('director_id', models.IntegerField(db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='Castings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ord', models.IntegerField()),
                ('actor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moviebuffstuff.actors')),
                ('movie_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moviebuffstuff.movies')),
            ],
        ),
    ]
